// Records the PayeeLock demo as a narrated video.
// Prereqs: `npm run serve` running on :4310 with AgentMail connected, narration wavs in .state/video
// (generated by scripts/narration.ps1), ffmpeg on PATH. Output: .state/video/payeelock-demo.mp4
//
//   node scripts/record-demo.mjs            # live email for every step
//   node scripts/record-demo.mjs --local    # "Run locally" instead of sending email

import { chromium } from "playwright";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const BASE = process.env.PAYEELOCK_URL ?? "http://localhost:4310";
const OUT = path.resolve(".state/video");
const LOCAL = process.argv.includes("--local");
const W = 1920, H = 1080;
const narration = JSON.parse(fs.readFileSync(path.join(OUT, "narration.json"), "utf8").replace(/^﻿/, ""));
const wavDuration = (f) => Number(execFileSync("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", f]).toString().trim());
const seg = Object.fromEntries(narration.map((n) => [n.id.slice(3), { ...n, file: path.join(OUT, n.id + ".wav"), dur: wavDuration(path.join(OUT, n.id + ".wav")) }]));

const CAPTIONS = {
  intro: "An AI agent that pays invoices. Two boundaries: a Wasmer sandbox and a payee-bound ledger.",
  legit: "Step 1 · Real vendor, real invoice · agent extracts in the sandbox · ledger pays the account on file",
  attack: "Step 2 · Look-alike sender, new bank, embedded script · sandbox denies exfil · ledger blocks $51,900",
  bankchange: "Step 3 · Real bank change · parked for callback · attacker's request rejected, vendor's verified",
  pay: "Step 4 · Next invoice pays to the newly verified account",
  close: "Built today: AgentMail listener, Wasmer boundary, payee-bound ledger, console, 15 tests",
};

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const timeline = [];
let t0;

const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: W, height: H }, deviceScaleFactor: 1, recordVideo: { dir: OUT, size: { width: W, height: H } }, colorScheme: "light" });
const page = await context.newPage();
t0 = Date.now();
const now = () => (Date.now() - t0) / 1000;

async function caption(text) {
  await page.evaluate((t) => {
    let el = document.getElementById("__cap");
    if (!el) {
      el = document.createElement("div");
      el.id = "__cap";
      el.style.cssText = "position:fixed;left:50%;bottom:28px;transform:translateX(-50%);max-width:72%;padding:12px 20px;background:rgba(20,20,18,.92);color:#f5f3ed;font:500 22px/1.35 Inter,system-ui,sans-serif;border-radius:6px;z-index:99999;letter-spacing:-0.005em;box-shadow:0 8px 30px rgba(0,0,0,.25)";
      document.body.appendChild(el);
    }
    el.textContent = t;
  }, text);
}

async function startSegment(key) {
  const s = seg[key];
  timeline.push({ key, start: now(), dur: s.dur, file: s.file });
  await caption(CAPTIONS[key]);
  console.log(`[${now().toFixed(1)}s] ${key} (${s.dur.toFixed(1)}s narration)`);
  return Date.now();
}
async function holdUntil(startedAt, key, extra = 0.6) {
  const remaining = seg[key].dur * 1000 + extra * 1000 - (Date.now() - startedAt);
  if (remaining > 0) await sleep(remaining);
}

async function selectScenario(index) { await page.click(`[data-select="${index}"]`); await sleep(500); }
async function runScenario(index, expectedClass) {
  const before = await page.locator("article.case").count();
  await selectScenario(index);
  const liveBtn = page.locator("#scenario-detail [data-send]");
  const useLive = !LOCAL && (await liveBtn.count()) && (await liveBtn.isEnabled());
  await (useLive ? liveBtn : page.locator("#scenario-detail [data-run]")).click();
  await sleep(600);
  try {
    await page.waitForFunction((n) => document.querySelectorAll("article.case").length > n, before, { timeout: useLive ? 45000 : 60000 });
  } catch {
    console.log("  live email did not arrive in time, falling back to local run");
    await selectScenario(index); await page.locator("#scenario-detail [data-run]").click(); await sleep(600);
    await page.waitForFunction((n) => document.querySelectorAll("article.case").length > n, before, { timeout: 60000 });
  }
  await page.waitForSelector(`article.case .stamp-${expectedClass}`, { timeout: 60000 });
  console.log(`  case arrived, verdict ${expectedClass} at ${now().toFixed(1)}s`);
}
async function openRow(text) {
  const btn = page.locator("article.case").first().locator(".row-head", { hasText: text }).first();
  if ((await btn.getAttribute("aria-expanded")) !== "true") await btn.click();
  await sleep(400);
  await btn.evaluate((el) => el.scrollIntoView({ block: "start", behavior: "smooth" }));
}

// ---- reset to a clean session
await page.goto(BASE, { waitUntil: "networkidle" });
await page.waitForSelector("#btn-reset");
await sleep(800);
await page.click("#btn-reset");
await page.waitForSelector("#action-dialog[open]");
await page.click("#dialog-submit");
await sleep(1200);

// ---- 1 intro
let t = await startSegment("intro");
await sleep(10000);
await selectScenario(1);
await sleep(3000);
await selectScenario(0);
await holdUntil(t, "intro");

// ---- 2 legit
t = await startSegment("legit");
await runScenario(0, "EXECUTED");
await sleep(3000);
await openRow("Wasmer sandbox");
await holdUntil(t, "legit");
await page.evaluate(() => window.scrollTo({ top: 0, behavior: "smooth" }));

// ---- 3 attack
t = await startSegment("attack");
await runScenario(1, "BLOCKED");
await sleep(7000);
await openRow("Wasmer sandbox");
await sleep(9000);
await openRow("Ledger");
await holdUntil(t, "attack");
await page.evaluate(() => window.scrollTo({ top: 0, behavior: "smooth" }));

// ---- 4 bank change + approvals
t = await startSegment("bankchange");
await runScenario(2, "PENDING_APPROVAL");
await sleep(2500);
const attackerCard = page.locator(".approval", { hasText: "look-alike" }).first();
await attackerCard.scrollIntoViewIfNeeded();
await attackerCard.locator("[data-reject]").click();
await page.waitForSelector("#reject-reason");
await page.fill("#reject-reason", "Called Dana Reyes at the number on file. Northwind did not request this change.");
await sleep(900);
await page.click("#dialog-submit");
await sleep(1500);
await page.locator(".approval [data-approve]").first().click();
await page.waitForSelector("#callback-confirmed");
await sleep(700);
await page.check("#callback-confirmed");
await sleep(700);
await page.click("#dialog-submit");
await sleep(1800);
await holdUntil(t, "bankchange", 1.0);

// ---- 5 pay
t = await startSegment("pay");
await runScenario(3, "EXECUTED");
await holdUntil(t, "pay", 1.5);

// ---- 6 close
t = await startSegment("close");
await page.evaluate(() => window.scrollTo({ top: 0, behavior: "smooth" }));
await sleep(6000);
const payees = page.locator("#vendors");
await payees.scrollIntoViewIfNeeded();
await sleep(8000);
await page.evaluate(() => window.scrollTo({ top: 0, behavior: "smooth" }));
await holdUntil(t, "close", 1.5);

const total = now();
await context.close();
const videoPath = await page.video().path();
await browser.close();
fs.writeFileSync(path.join(OUT, "timeline.json"), JSON.stringify({ total, timeline }, null, 2));
console.log(`recorded ${total.toFixed(1)}s -> ${videoPath}`);

// ---- mux narration: each segment delayed to the moment its caption appeared
const inputs = ["-i", videoPath];
const filters = [];
timeline.forEach((s, i) => {
  inputs.push("-i", s.file);
  filters.push(`[${i + 1}:a]adelay=${Math.round(s.start * 1000)}:all=1[a${i}]`);
});
filters.push(`${timeline.map((_, i) => `[a${i}]`).join("")}amix=inputs=${timeline.length}:normalize=0:dropout_transition=0[mix]`);
const out = path.join(OUT, "payeelock-demo.mp4");
execFileSync("ffmpeg", ["-y", ...inputs, "-filter_complex", filters.join(";"), "-map", "0:v", "-map", "[mix]", "-c:v", "libx264", "-preset", "medium", "-crf", "20", "-pix_fmt", "yuv420p", "-r", "30", "-c:a", "aac", "-b:a", "128k", "-shortest", out], { stdio: "inherit" });
console.log("wrote", out);
